name: ai_text_game
description: A text based adventure game.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  internet_connection_checker_plus: ^2.1.0
  dartz: ^0.10.1
  get_it: ^7.6.0
  package_info_plus: ^5.0.1
  flutter_screenutil: ^5.9.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: ZenDots
      fonts:
        - asset: assets/fonts/ZenDots/ZenDots-Regular.ttf
          weight: 400
          style: normal
